//! Private mapping from pronunciation choices to engine voices.

use g2p_types::Language;

pub(crate) const ESPEAK_VOICES: &[(Language, &str)] = &[
    (Language::English, "en-us"),
    (Language::German, "de"),
    (Language::French, "fr-fr"),
    (Language::Italian, "it"),
    (Language::PortugueseBrazil, "pt-br"),
    (Language::SpanishEuro, "es"),
    (Language::Russian, "ru"),
    (Language::Albanian, "sq"),
    (Language::Arabic, "ar"),
    (Language::Armenian, "hy"),
    (Language::Cantonese, "yue"),
    (Language::Croatian, "hr"),
    (Language::Czech, "cs"),
    (Language::Danish, "da"),
    (Language::Persian, "fa"),
    (Language::Dutch, "nl"),
    (Language::Finnish, "fi"),
    (Language::HaitianCreole, "ht"),
    (Language::Hebrew, "he"),
    (Language::Hungarian, "hu"),
    (Language::Icelandic, "is"),
    (Language::Indonesian, "id"),
    (Language::Irish, "ga"),
    (Language::Greek, "el"),
    (Language::Norwegian, "nb"),
    (Language::Polish, "pl"),
    (Language::Punjabi, "pa"),
    (Language::Romanian, "ro"),
    (Language::Swahili, "sw"),
    (Language::Swedish, "sv"),
    (Language::Turkish, "tr"),
    (Language::Ukrainian, "uk"),
    (Language::Urdu, "ur"),
    (Language::Vietnamese, "vi"),
    (Language::SpanishLatinAmerica, "es-419"),
    (Language::PortugueseEuro, "pt"),
];
